{ lib, pkgs, config, inputs, ... }:
let
  mkCfg = mod:
    let
      defaults = if mod ? options && mod.options != null && (mod.options._type or null) == "option" then (mod.options.default or { }) else { };
    in
    lib.recursiveUpdate defaults { enable = true; };

  adapt = path:
    let
      raw = import path;
      mod = if builtins.isFunction raw then raw { inherit lib pkgs config inputs; } else raw;
    in
    if mod ? system then
      mod.system { inherit lib pkgs config inputs; cfg = mkCfg mod; nixul = config.nixul; }
    else
      null;
in
{
  imports = lib.filter (x: x != null) [
    (adapt ../../modules/apps/gaming/compatibility/proton.nix)
    (adapt ../../modules/apps/gaming/compatibility/winboat.nix)
    (adapt ../../modules/apps/gaming/compatibility/wine.nix)
    (adapt ../../modules/apps/gaming/platform/gamemode.nix)
    (adapt ../../modules/apps/gaming/platform/gamescope.nix)
    (adapt ../../modules/apps/gaming/platform/steam.nix)
    (adapt ../../modules/apps/media/audio/pamixer.nix)
    (adapt ../../modules/apps/media/audio/pavucontrol.nix)
    (adapt ../../modules/apps/media/audio/playerctl.nix)
    (adapt ../../modules/apps/media/audio/pulsemixer.nix)
    (adapt ../../modules/apps/media/photo/aseprite.nix)
    (adapt ../../modules/apps/media/photo/gimp.nix)
    (adapt ../../modules/apps/media/photo/lutgen.nix)
    (adapt ../../modules/apps/media/video/ffmpeg.nix)
    (adapt ../../modules/apps/system/disk/gparted.nix)
    (adapt ../../modules/apps/system/files/analyzers/baobab.nix)
    (adapt ../../modules/apps/system/files/analyzers/ncdu.nix)
    (adapt ../../modules/apps/system/files/archives/file-roller.nix)
    (adapt ../../modules/apps/system/files/archives/p7zip.nix)
    (adapt ../../modules/apps/system/files/archives/unzip.nix)
    (adapt ../../modules/apps/system/files/managers/nautilus.nix)
    (adapt ../../modules/apps/system/monitors/lnav.nix)
    (adapt ../../modules/apps/system/monitors/mission-center.nix)
    (adapt ../../modules/apps/user/internet/browsers/chrome.nix)
    (adapt ../../modules/apps/user/internet/browsers/tor.nix)
    (adapt ../../modules/apps/user/internet/communication/telegram.nix)
    (adapt ../../modules/apps/user/internet/communication/thunderbird.nix)
    (adapt ../../modules/apps/user/internet/qbitttorrent.nix)
    (adapt ../../modules/apps/user/productivity/libreoffice.nix)
    (adapt ../../modules/apps/user/productivity/obsidian.nix)
    (adapt ../../modules/apps/user/productivity/todoist.nix)
    (adapt ../../modules/core/maintenance/auto-upgrade.nix)
    (adapt ../../modules/core/maintenance/journald.nix)
    (adapt ../../modules/core/security/access/fail2ban.nix)
    (adapt ../../modules/core/security/access/polkit.nix)
    (adapt ../../modules/core/security/network/acme.nix)
    (adapt ../../modules/core/security/network/adguardhome.nix)
    (adapt ../../modules/core/security/network/avahi.nix)
    (adapt ../../modules/core/security/network/firewall.nix)
    (adapt ../../modules/core/security/network/unbound.nix)
    (adapt ../../modules/core/security/secrets/sops.nix)
    (adapt ../../modules/core/security/ssh/openssh.nix)
    (adapt ../../modules/core/security/sysctl.nix)
    (adapt ../../modules/core/system/boot/grub.nix)
    (adapt ../../modules/core/system/desktop/dbus.nix)
    (adapt ../../modules/core/system/desktop/xdg.nix)
    (adapt ../../modules/core/system/identity/locale.nix)
    (adapt ../../modules/core/system/identity/user.nix)
    (adapt ../../modules/core/system/nix/documentation.nix)
    (adapt ../../modules/core/system/nix/nh.nix)
    (adapt ../../modules/core/system/nix/nix-index.nix)
    (adapt ../../modules/core/system/nix/nix-ld.nix)
    (adapt ../../modules/core/system/nix/nix.nix)
    (adapt ../../modules/core/terminal/shells/fish.nix)
    (adapt ../../modules/core/terminal/shells/zsh.nix)
    (adapt ../../modules/core/terminal/tools/monitor/tcpdump.nix)
    (adapt ../../modules/core/terminal/tools/navigation/ripgrep.nix)
    (adapt ../../modules/desktop/components/notifications/ntfy.nix)
    (adapt ../../modules/desktop/display/wayland.nix)
    (adapt ../../modules/desktop/display/xserver.nix)
    (adapt ../../modules/desktop/display-manager/gdm.nix)
    (adapt ../../modules/desktop/theming/catppuccin-mocha.nix)
    (adapt ../../modules/desktop/theming/gruvbox-material.nix)
    (adapt ../../modules/desktop/theming/rose-pine.nix)
    (adapt ../../modules/dev/editor/antigravity.nix)
    (adapt ../../modules/dev/git/git-extras.nix)
    (adapt ../../modules/dev/git/lazygit.nix)
    (adapt ../../modules/dev/runtimes/cpp.nix)
    (adapt ../../modules/dev/runtimes/go.nix)
    (adapt ../../modules/dev/runtimes/javascript/bun.nix)
    (adapt ../../modules/dev/runtimes/javascript/nodejs.nix)
    (adapt ../../modules/dev/runtimes/javascript/prisma.nix)
    (adapt ../../modules/dev/runtimes/python.nix)
    (adapt ../../modules/dev/runtimes/rustc.nix)
    (adapt ../../modules/dev/runtimes/zig.nix)
    (adapt ../../modules/dev/security/attack/brute-force/hashcat.nix)
    (adapt ../../modules/dev/security/attack/brute-force/hydra.nix)
    (adapt ../../modules/dev/security/attack/brute-force/john.nix)
    (adapt ../../modules/dev/security/attack/exploit/metasploit.nix)
    (adapt ../../modules/dev/security/attack/exploit/websploit.nix)
    (adapt ../../modules/dev/security/attack/mitm/bettercap.nix)
    (adapt ../../modules/dev/security/attack/mitm/ettercap.nix)
    (adapt ../../modules/dev/security/recon/discovery/assetfinder.nix)
    (adapt ../../modules/dev/security/recon/discovery/sherlock.nix)
    (adapt ../../modules/dev/security/recon/discovery/subfinder.nix)
    (adapt ../../modules/dev/security/recon/web/katana.nix)
    (adapt ../../modules/dev/security/recon/web/whatweb.nix)
    (adapt ../../modules/dev/security/scanning/network/inetutils.nix)
    (adapt ../../modules/dev/security/scanning/network/netcat.nix)
    (adapt ../../modules/dev/security/scanning/vulnability/nuclei.nix)
    (adapt ../../modules/dev/security/trafic/burbsuite.nix)
    (adapt ../../modules/dev/security/trafic/caido.nix)
    (adapt ../../modules/dev/security/wireless/wifite2.nix)
    (adapt ../../modules/dev/tools/db/dbeaver.nix)
    (adapt ../../modules/dev/tools/db/usql.nix)
    (adapt ../../modules/dev/tools/http/client/bruno.nix)
    (adapt ../../modules/dev/tools/http/client/hurl.nix)
    (adapt ../../modules/dev/tools/http/client/simplehttp.nix)
    (adapt ../../modules/dev/tools/http/client/xh.nix)
    (adapt ../../modules/dev/tools/http/server/ngrok.nix)
    (adapt ../../modules/dev/tools/quality/biome.nix)
    (adapt ../../modules/dev/tools/quality/deadnix.nix)
    (adapt ../../modules/hardware/audio/pipewire.nix)
    (adapt ../../modules/hardware/audio/rtkit.nix)
    (adapt ../../modules/hardware/bluetooth/blueman.nix)
    (adapt ../../modules/hardware/bluetooth/bluetooth.nix)
    (adapt ../../modules/hardware/inputs/qmk.nix)
    (adapt ../../modules/hardware/inputs/via.nix)
    (adapt ../../modules/hardware/network/networkmanager.nix)
    (adapt ../../modules/hardware/power/brightnessctl.nix)
    (adapt ../../modules/hardware/power/power-management.nix)
    (adapt ../../modules/hardware/power/profiles.nix)
    (adapt ../../modules/hardware/power/thermald.nix)
    (adapt ../../modules/hardware/power/upower.nix)
    (adapt ../../modules/hardware/printing/hplip.nix)
    (adapt ../../modules/hardware/printing/printing.nix)
    (adapt ../../modules/hardware/printing/sane.nix)
    (adapt ../../modules/hardware/units/cpu/amd.nix)
    (adapt ../../modules/hardware/units/cpu/intel.nix)
    (adapt ../../modules/hardware/units/gpu/mesa.nix)
    (adapt ../../modules/hardware/units/gpu/nvidia.nix)
    (adapt ../../modules/hardware/units/gpu/opengl.nix)
    (adapt ../../modules/hardware/units/ram/zram.nix)
    (adapt ../../modules/hardware/units/storage/usb-automount.nix)
    (adapt ../../modules/services/ai/litellm.nix)
    (adapt ../../modules/services/ai/ollama.nix)
    (adapt ../../modules/services/ai/open-webui.nix)
    (adapt ../../modules/services/ai/openclaw.nix)
    (adapt ../../modules/services/containers/docker.nix)
    (adapt ../../modules/services/containers/kubernetes/kind.nix)
    (adapt ../../modules/services/containers/kubernetes/kubectl.nix)
    (adapt ../../modules/services/containers/kubernetes/minikube.nix)
    (adapt ../../modules/services/containers/podman.nix)
    (adapt ../../modules/services/databases/postgresql.nix)
    (adapt ../../modules/services/databases/redis.nix)
    (adapt ../../modules/services/monitoring/dashy.nix)
    (adapt ../../modules/services/monitoring/glance.nix)
    (adapt ../../modules/services/server/nginx.nix)
    (adapt ../../modules/services/server/vaultwarden.nix)
    (adapt ../../modules/services/vpn/openvpn.nix)
    (adapt ../../modules/services/vpn/tailscale.nix)
    (adapt ../../modules/services/vpn/wireguard.nix)
  ];
}
