{
  imports = [
    ./ai.nix
    ./autopairs.nix
    ./blink.nix
    ./bufferline.nix
    ./editing.nix
    ./formatting.nix
    ./git.nix
    ./lint.nix
    ./lsp.nix
    ./markdown.nix
    ./navigation.nix
    ./snacks.nix
    ./telescope.nix
    ./terminal.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./trouble.nix
    ./typescipt-tools.nix
    ./ui.nix
  ];
}
