{
  plugin = [
    "@gotgenes/opencode-agent-identity"
    "opencode-antigravity-auth"
    "opencode-multi-openai-codex-auth"
    "opencode-agent-skills"
    "opencode-websearch"
    "@nick-vi/opencode-type-inject"
    "@tarquinen/opencode-dcp"
    "@morphllm/opencode-morph-plugin"
    "@zenobius/opencode-skillful"
    "@plannotator/opencode"
    "@spoons-and-mirrors/subtask2"
    "opencode-memory"
    "opencode-agent-memory"
    "opencode-git-context"
    "opencode-mystatus"
    "@ramtinj95/opencode-tokenscope"
    "open-trees"
  ];
}
