{
  imports = [
    ./autopairs.nix
    ./blink.nix
    ./bufferline.nix
    ./development.nix
    ./editing.nix
    ./formatting.nix
    ./git.nix
    ./lsp.nix
    ./navigation.nix
    ./persistence.nix
    ./telescope.nix
    ./terminal.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./trouble.nix
    ./ui.nix
  ];
}
